# docker compose up --build percona
version: "3"
services:
  percona:
    container_name: pam-oauth2-percona
    build:
      context: .
      dockerfile: docker/percona.dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=password
    env_file:
      - .env
    command: /docker-entrypoint.sh mysqld
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 30s
      retries: 5
      interval: 15s
    ports:
      - 3306:3306
    volumes:
      - ./tests/test.py:/opt/test.py
      - ./config/libpam_oidc.yaml:/etc/datajoint/libpam_oidc.yaml
    depends_on:
      builder:
        condition: service_completed_successfully
    image: datajoint/pam-oauth2-percona:${DOCKER_TAG:-v0.1.4}
  builder:
    container_name: pam-oauth2-builder
    build:
      context: .
      dockerfile: docker/builder.dockerfile
    image: datajoint/pam-oauth2-builder:${DOCKER_TAG:-v0.1.4}
