name: Create Versioned Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          docker compose build builder
          mkdir -p pam-oidc/bin
          docker compose cp builder:/tmp/pam-oauth2/libpam_oidc_gnu.so ./pam-oidc/bin/
          docker compose cp builder:/tmp/pam-oauth2/libpam_oidc_musl.so ./pam-oidc/bin/
      - name: Touch Changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: touch "${{ github.workspace }}/docs/CHANGELOG-${{ github.ref_name }}.md"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./pam-oidc/bin/libpam_oidc_gnu.so
            ./pam-oidc/bin/libpam_oidc_musl.so
          body_path: ${{ github.workspace }}/docs/CHANGELOG-${{ github.ref_name }}.md